### ISSUE TITLE
Support for Laravel 5.6?

### ISSUE THREAD

**Issue by drmzio** [swisnl/laravel-javascript-data-response#1]
Tried installing this package for Laravel 5.6 but it only supports 5.5 or lower. Are there plans to support newer versions of Laravel?

![](https://cl.ly/cf72506c1ada/Image%2525202018-09-07%252520at%2525201.41.42%252520AM.png)

**Comment by JaZo** [comment]
Hi @drmzio, thanks for trying this package! I'm currently working on a PR to add Laravel 5.6 and 5.7 support. You can expect a new release soon.

**Comment by JaZo** [comment]
@drmzio, I have just released 1.0.0 which includes support for Laravel 5.6 and 5.7.
